context:
  version: "2.11.0"

package:
  name: tensorizer
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/tensorizer/tensorizer-${{ version }}.tar.gz
    sha256: 5f726594656459974219c001bad6dcca6d3d441d47b9f12b342ba9686a98f45a

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - pytorch >=1.9.0
    - numpy >=1.19.5
    - protobuf >=3.19.5
    - psutil >=5.9.4
    - boto3 >=1.26.0
    - redis-py >=4.5.5
    - hiredis >=2.2.0
    - libnacl-python-bindings >=2.1.0

tests:
  - python:
      imports:
        - tensorizer
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest
        - pytest-rerunfailures
        - transformers >=4.27.1
        - moto >=4.1.4,<5.0.0
        - redis-py >=5.0.0
        - if: not win
          then:
            - redis-server
        - boto3
    script:
    # Redis tests are flaky, sometimes failing with:
    #     redis.exceptions.ConnectionError: Error 111 connecting to localhost:6381.
    #     Connection refused.
    # I suspect that there's not enough startup time, so we retry a few times.
      - if: linux
        then:
          # Skip test_download_url until <https://github.com/coreweave/tensorizer/pull/188> is merged.
          - pytest tests -vvv --reruns 2 --deselect tests/test_stream_io.py::TestS3::test_download_url
        else:
          - echo Skipping tests

about:
  homepage: https://github.com/coreweave/tensorizer
  repository: https://github.com/coreweave/tensorizer
  summary: A tool for fast PyTorch module, model, and tensor serialization + deserialization.
  description: Module, Model, and Tensor Serialization/Deserialization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
